### ISSUE TITLE
A volte le annoCard collassano in malo modo

### ISSUE THREAD

**Issue by eduSan** [418imateapot/new-raschietto#12]
Non mi e' chiaro in che circostanze succede, forse solo in stagingArea (annotazioni non salvate)?
Comunque a volte, in genere quando c'e' una sola annotazione, la card collassa su se stessa e il testo straborda.

**Comment by eduSan** [comment]
Possibilmente risolto con b5217a21c7b2414cda31d4333ffa4316df5ac87f ?

**Comment by eduSan** [comment]
In realtà adesso le card con tanto testo occupano troppo spazio...

**Comment by Burlollone** [comment]
Effetto collaterale del'orario a fondo card, ma la cosa sembra essere risolta
