### ISSUE TITLE
se passi da annotator a reader non ricarica le annotazioni sul testo

### ISSUE THREAD

**Issue by patmha** [418imateapot/new-raschietto#17]

**Comment by patmha** [comment]
e nemmeno il viceversa. il che potrebbe essere preoccupante: uno carica un documento con le annotazioni, ne vuole aggiungere una nuova, passa ad annotator e si trova a dover ricaricare la pagina. il genere di cosa che noterebbe il prof

**Comment by patmha** [comment]
e nemmeno dopo che ti logghi.

**Comment by eduSan** [comment]
Dovrei averlo risolto con 8e034e057043cd7253b0b712a552f40f9164fd71
Non è una soluzione molto elegante ma dovrebbe funzionare fino a mercoledì =D
